<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.udaya-technology.admin-system</groupId>
	<artifactId>admin-system</artifactId>
	<version>1.82</version>
	<packaging>war</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<npm.output.directory>.output/public</npm.output.directory>
	</properties>

	<build>
		<finalName>${project.artifactId}##V${project.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
				<configuration>
					<webResources>
						<resource>
							<directory>${npm.output.directory}</directory>
						</resource>
					</webResources>
					<webXml>${basedir}/web.xml</webXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.3.2</version>
				<executions>
					<execution>
						<id>yarn install (initialize)</id>
						<goals>
							<goal>exec</goal>
						</goals>
						<phase>initialize</phase>
						<configuration>
							<executable>pnpm</executable>
							<arguments>
								<argument>install</argument>
							</arguments>
						</configuration>

					</execution>
					<execution>
						<id>yarn install (clean)</id>
						<goals>
							<goal>exec</goal>
						</goals>
						<phase>pre-clean</phase>
						<configuration>
							<executable>pnpm</executable>
							<arguments>
								<argument>install</argument>
							</arguments>
						</configuration>

					</execution>
					<execution>
						<id>yarn build (compile)</id>
						<goals>
							<goal>exec</goal>
						</goals>
						<phase>compile</phase>
						<configuration>
							<executable>pnpm</executable>
							<arguments>
								<argument>generate</argument>
							</arguments>
						</configuration>

					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
